#!/bin/bash
set -e

# current script directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "${DIR}/.."

rm -rf dist/*

python3 setup.py sdist bdist_wheel
python3 -m twine upload dist/*
