name: onboard.client
on:
  push:
    branches: dev
  pull_request:
jobs:
  tox:
    runs-on: [ubuntu-22.04]
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install tox
        run: pip install tox
      - name: Stylecheck (flake8)
        run: tox -e flake8
      - name: Test (pytest)
        run: tox -e py3
      - name: Typecheck (mypy)
        run: tox -e mypy
